# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aka < Formula
  desc "Manage shell aliases from the terminal with a TUI"
  homepage "https://github.com/aaangelmartin/aka"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.0.0/aka_1.0.0_darwin_amd64.tar.gz"
      sha256 "b15bae8e9cbdc1e63e9b91180740f8901cf7526aa5b6c6d7e442d58bb581f19d"

      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.0.0/aka_1.0.0_darwin_arm64.tar.gz"
      sha256 "8f0275da9acdbd1e44a9fd0644fffe9af3c6b6d3ee14e6e2c72d77371a64147e"

      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.0.0/aka_1.0.0_linux_amd64.tar.gz"
      sha256 "5e868ca6bcf1ec31626568104befdb082f2c880c372726dee4e0101aafd75ea2"
      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.0.0/aka_1.0.0_linux_arm64.tar.gz"
      sha256 "8e0c6a9eea1ce6d3003d985aebba0be4ec2e45e25f174e8eacd0cf50374b83d3"
      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
  end

  test do
    assert_match "aka", shell_output("#{bin}/aka version")
  end
end
