# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aka < Formula
  desc "Manage shell aliases from the terminal with a TUI"
  homepage "https://github.com/aaangelmartin/aka"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.1.0/aka_1.1.0_darwin_amd64.tar.gz"
      sha256 "e434c82c416fe1ffdd8a4d75091597787af9a13613a70eb1b176cab22c8387f2"

      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.1.0/aka_1.1.0_darwin_arm64.tar.gz"
      sha256 "7c9cf0a4afa33cf29b9b3da45dc0e33ed997a9ead34b6d5707af7c36c1427419"

      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.1.0/aka_1.1.0_linux_amd64.tar.gz"
      sha256 "39709ebff777c392c7df6032762e59e2237077fea46d7153c7fce85e3179aa93"
      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/aka/releases/download/v1.1.0/aka_1.1.0_linux_arm64.tar.gz"
      sha256 "19daebed75ba8d235480d696503a49cdecbe275c0bd6e3acdbeb40f13031e355"
      define_method(:install) do
        bin.install "aka"
        generate_completions_from_executable(bin/"aka", "completion")
      end
    end
  end

  test do
    assert_match "aka", shell_output("#{bin}/aka version")
  end
end
