# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goto < Formula
  desc "Open URLs and manage link aliases from the terminal"
  homepage "https://github.com/aaangelmartin/GoTo"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.3.0/goto_0.3.0_darwin_amd64.tar.gz"
      sha256 "d0c0a968bf71e8375fb8dee5c4b8b1215bcfc63f3965769bbb87c0a8e4ccfb74"

      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.3.0/goto_0.3.0_darwin_arm64.tar.gz"
      sha256 "5f22958b5b4f9e3d47ae2ad0d7a0ff347a73171bda5b30cc31569acbde3ca97c"

      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.3.0/goto_0.3.0_linux_amd64.tar.gz"
      sha256 "38cdc1c33360ab0ab2d3058a774d56f5e456398458ec59b30ce43bd06469fd06"
      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.3.0/goto_0.3.0_linux_arm64.tar.gz"
      sha256 "ef8f3f15bb45c89839db210a366752c0817e2c6761f0b55ab8872a7f5b42b904"
      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
  end

  test do
    assert_match "goto", shell_output("#{bin}/goto version")
  end
end
