# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goto < Formula
  desc "Open URLs and manage link aliases from the terminal"
  homepage "https://github.com/aaangelmartin/GoTo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.1.0/goto_0.1.0_darwin_amd64.tar.gz"
      sha256 "5b693679c26cb33a08f35a9f33abdf403da9a07d3c260378b3b84601cd64a00d"

      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.1.0/goto_0.1.0_darwin_arm64.tar.gz"
      sha256 "c4ecaf2e16e03c4e6cd41d290655921baa6497702b2e4fcb51c5cf1e554472ab"

      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.1.0/goto_0.1.0_linux_amd64.tar.gz"
      sha256 "e145ec4698ebac1a6cf6cc0cae93a189f1303103fbafb2d29f0c000ff9d166f9"
      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaangelmartin/GoTo/releases/download/v0.1.0/goto_0.1.0_linux_arm64.tar.gz"
      sha256 "fb73e71e738b3f15561320032453109a09bc886205938fbd1768638fddcb1c95"
      define_method(:install) do
        bin.install "goto"
        generate_completions_from_executable(bin/"goto", "completion")
      end
    end
  end

  test do
    assert_match "goto", shell_output("#{bin}/goto version")
  end
end
